name: django
on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

permissions:
 id-token: write # This is required for requesting the JWT
 contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: build and release to DockerHub
        env:
          NAME: ${{secrets.DOCKERHUB_USERNAME}}
          REPO: djangoecs
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REPO .
          docker tag $REPO:latest $NAME/$REPO:$IMAGE_TAG
          docker push $NAME/$REPO:$IMAGE_TAG

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335547094:role/djangoECSrole
          role-session-name: djangoECSrole 
          aws-region: ap-northeast-2